# Generated by Django 2.2.6 on 2019-12-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('featured', models.BooleanField()),
            ],
        ),
    ]
