# Generated by Django 2.2.6 on 2019-12-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
