# Generated by Django 2.2.6 on 2019-12-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191213_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Product Images'),
        ),
    ]
