# Generated by Django 2.2.6 on 2019-12-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191213_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='featured',
        ),
    ]
