# Generated by Django 2.2.6 on 2019-12-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_products_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='ProductName',
            field=models.CharField(max_length=50),
        ),
    ]
